# This is a basic workflow to help you get started with Actions

name: BuildTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up environment
      - name: Set Up Environment
        run: echo Good

      # Download and Install Arduino Compiler
      - name: Install Arduino Compiler
        run: |
          wget https://downloads.arduino.cc/arduino-1.6.8-linux64.tar.xz
          tar xf arduino-1.6.8-linux64.tar.xz
          sudo mv arduino-1.6.8 /usr/local/share/arduino
          sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

      # Compile and Run Tests
      - name: Compile and Run Tests
        run: |
          export DISPLAY=:1
          sudo Xvfb -- :1 -ac -screen 0 1280x1024x16 > /dev/null 2>&1 &
          sleep 3
          ln -s $GITHUB_WORKSPACE /usr/local/share/arduino/libraries/TM1637TinyDisplay
          arduino --verify --board arduino:avr:uno --pref sketchbook.path="$PWD" $PWD/examples/TM1637Test/TM1637Test.ino
          arduino --verify --board arduino:avr:uno --pref sketchbook.path="$PWD" $PWD/examples/TM1637-6Digit-Test/TM1637-6Digit-Test.ino
          arduino --verify --board arduino:avr:uno --pref sketchbook.path="$PWD" $PWD/examples/ATtiny85/ATtiny85.ino
